spring.application.name=dataflow-realtime-processor
server.port=8080

# JPA & MySQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# RabbitMQ configuration
dataflow.rabbitmq.exchange=dataflow.orders.exchange
dataflow.rabbitmq.queue=dataflow.orders.queue
dataflow.rabbitmq.routingkey=dataflow.orders.key

# Simulation
dataflow.simulation.enabled=true
dataflow.simulation.rate-ms=2000

# Actuator Endpoints Configuration
management.endpoints.web.exposure.include=health,metrics,prometheus,info
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

# Tanzu OTel Metrics Configuration Defaults
tanzu.metrics.jvm.enabled=true
tanzu.metrics.jvm.endpoint=https://otel-collector:9565/v1/metrics
tanzu.metrics.custom.enabled=true
tanzu.metrics.custom.endpoint=https://otel-collector:9566/v1/metrics
